### ISSUE TITLE
I've got code for ragtime migrations with pg2

### ISSUE THREAD

**Issue by teodorlu** [igrishaev/pg2#1]
Hi!

Thank you for this awesome library. I've used it a tiny bit, and I love that I get the raw PostgreSQL experience rather than what JDBC passes through.

I recently wrote some code to migrate a PostgreSQL database with pg2 and https://github.com/weavejester/ragtime/:

﻿﻿https://github.com/iterate/mikrobloggeriet/tree/2eae5062578cbd1256b2558a34d0b8e781a474d6/src/mikrobloggeriet/db/migrate.clj

I'm happy to contribute documentation on "how to migrate schemas with ragtime and pg2" if you find that useful. I'm aware that `pg2` is early in its development, it might make more sense to focus on the rest of the docs (eg JSON support) before migrations.

I'm also curious about what you plans are for migrations. Whether you intend to provide an API for migrating schemas, or if you plan to leave that to userspace.

Teodor

**Comment by teodorlu** [comment]
Unrelated note: I find that I prefer

```clojure
(with-open [conn (pg/connect config)]
  (pg/query conn "select 1 as one"))
```

to

```clojure
(pg/with-connection [conn config]
  (pg/query conn "select 1 as one"))
```

. _Slightly_ more letters to write. But I don't have to remember macros names (`with-connection` and `with-statement`), and I don't have to worry about configuring my editor to help me understand those macros.

**Comment by igrishaev** [comment]
Hi Teodor! Yes, Ragtime support would be useful, and I had this idea in mind. Extending Migratus is not an options as it's completely bound to Next.JDBC without an option to bypass it somehow. So Ragtime is the right choice.

I think you can contribute in this way. Let's have a `pg-ragtime` subproject that depends on the Ragtime library and pg-core. In that package, you create the  `pg.ragtime` namespace that extends the Ragtime protocols.

**Comment by teodorlu** [comment]
Awesome!

Do you want me to put together a PR now?

**Comment by igrishaev** [comment]
I can create a skeletor of this project, and then you contribute. Ideally, we need to have integration tests. All together, there list is:

- create the pg-ragtime subpackage
- add integration tests
- make it compatible deps CLI via the -main function
- maybe a lein plugin?
- add it to the docs

**Comment by igrishaev** [comment]
Yes please create, any help is appreciated.

**Comment by teodorlu** [comment]
OK, great.

> I can create a skeletor of this project, and then you contribute.

If you can create a skeleton and then I can put my code into the namespace you create, that would probably be best.

**Comment by igrishaev** [comment]
I'll try to find some time tomorrow for the skeleton.

**Comment by teodorlu** [comment]
I'll start pulling out a draft API for PG2 from the application code in the meanwhile.

**Comment by teodorlu** [comment]
I started here: https://github.com/igrishaev/pg2/pull/3/files

### Should the user control which table to use for migrations, or PG2 decide?

I'm not quite sure, but I think it makes sense that a user has to explicitly opt in to choose which table name to use for ragtime. Perhaps this could be controlled with the other options to `pg/connect`.

What do you think?

**Comment by igrishaev** [comment]
@teodorlu I think this issue is not relevant any longer as PG2 ships its own migration engine (see release 1.5.0 and the "Migrations" section in readme). Would you mind if I close this issue and the related PR?

**Comment by teodorlu** [comment]
Agreed, closing issue and PR.

I think the migrations API you've made looks great, I'm looking forward to using it. I like that you were able to avoid the ragtime dependency!

Sorry that I wasn't able to put more time into my own migration code efforts.
