### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by thenonameguy** [igrishaev/pg2#10]
Absolutely awesome work. How do you plan on licensing the code?

As it stands it's not usable for any projects.

**Comment by thenonameguy** [comment]
Ah, sorry, I noticed now in the [project.clj file](https://github.com/igrishaev/pg2/blob/master/project.clj#L6-L8).
Please add it to the Github repo with a mentioned file so it's more apparent. Thanks!

**Comment by thenonameguy** [comment]
Also please add a [funding option](https://github.com/sponsors), I would like to donate to support the ongoing development.

**Comment by igrishaev** [comment]
Hm, I'm not too familiar with various licenses. Let me think for a while.

**Comment by thenonameguy** [comment]
Thanks for looking into it, it's quite important.

If you kept the current [EPL2 license](https://www.eclipse.org/legal/epl-2.0/), that would be fine for the time being.
Alternatively, this site has some good options:
https://choosealicense.com/licenses/

Generally, MPL 2.0 and MIT are good enough (depends on your goals/preferences).
EPL is common in Clojure as the language code is itself licensed with it.

**Comment by igrishaev** [comment]
Well, let it be Unlicensed meaning it's a public domain (see the LICENSE file added).
