### ISSUE TITLE
Hugsql adapter missing def-sqlvec-fns

### ISSUE THREAD

**Issue by kanwei** [igrishaev/pg2#11]
We'd love to attempt to switch to pg2 but the current Hugsql adapter is missing ```def-sqlvec-fns```, which is very commonly used by Hugsql users.

**Comment by igrishaev** [comment]
Hi! Sorry for some delay, I was traveling abroad. Yes I think I'll add it soon.

**Comment by igrishaev** [comment]
I believe it as been done, please find the new section in the docs: https://github.com/igrishaev/pg2/blob/def-sqlvec-fns/docs/hugsql.md#defining-sqlvec-functions

Let me know if you need something more!
