### ISSUE TITLE
Nested `pool/with-connection`

### ISSUE THREAD

**Issue by seriousbusinessuser** [igrishaev/pg2#13]
It would be really nice if `pool/with-connection` could ignore nested `pool/with-connection`'s otherwise, in some situations, it's hard to get the same connection previously obtained from the top level `pool/with-connection` to keep working in the same transaction.

**Comment by igrishaev** [comment]
Hm, that one sounds quite strange to me. How can you have nested `pool/with-connection` expressions? I know it's possible technically but I think one should avoid this at any cost. Usually, you obtain a connection, do the logic, and return the connection back.

Maybe you share some code fragments?

**Comment by seriousbusinessuser** [comment]
@igrishaev Yeah, this might seem strange and I didn't find an example of such behavior in JDBC but certain application architectures could benefit from this. 

For example if you have a clean separation of concerns in your application you might end up with several logical layers such business logic layer, data management layer and interface layer(e.g., HTTP API). Each of these layers should know as little as possible about each other. Control flow would look something like this: interface -> business logic -> data layer. (Module dependency graph would different, see https://blog.cleancoder.com/uncle-bob/2012/08/13/the-clean-architecture.html)

The problem is that business logic layer, primary user of the data layer, shouldn't know about DB connections or any other low level data layer detail, so if we instantiate DB connection on each HTTP request inside request handler and pass this connection through business logic layer to data layer then we would leak data layer implementation details to two unrelated application layers. 

To achieve this separation it is tempting to move DB connection instantiation to the data layer, so that only the data layer is responsible for grabbing a connection from the pool and doing its work. But doing it this way leads us to possibility of nested `with-connection` calls within data layer in situations similar to the one I described in https://github.com/igrishaev/pg2/issues/12#issuecomment-2227427536, just replace "transaction" with "connection".

**Comment by igrishaev** [comment]
Since #12 has been fixed, I'd like to ask if this one is still actual. I've been thinking about a case with two nested `pool/with-connection` macros but I could not. Of course, it's possible but to me, it clearly signals about something wrong in the code. One should never mix a pool and a connection because it leads to a mess.

**Comment by igrishaev** [comment]
Closing as I'm not sure if it's really needed.
