### ISSUE TITLE
Type Inference Error with JSONB Functions and Parameters in pg2

### ISSUE THREAD

**Issue by tomer8888** [igrishaev/pg2#17]
Issue Description:

Summary:

I'm experiencing a type inference error when using the pg2 library with PostgreSQL JSONB functions that involve parameters. Specifically, when using functions like jsonb_array_elements and operators like ->>, PostgreSQL throws a polymorphic type error due to parameters being of type unknown.

This issue does not occur when using next.jdbc and honeysql, suggesting that it might be related to how pg2 handles parameter binding and type inference.

Steps to Reproduce:

    Setup:
        PostgreSQL table test_table with a jsonb column data containing an array of JSON objects.
        Example data in data column:

        json

    [
      {"score": "10", "quality": "high"},
      {"score": "8", "quality": "medium"}
    ]

Clojure Code Using pg2:

clojure

    (require '[pg.jdbc :as jdbc]
             '[pg.honey :as sql])

    (def ds ; your database datasource)

    (def query
      {:select [[:->> :issue "score"] :score]
       :from   [[[:jsonb_array_elements :data] :issue]]
       :where  [:= [:->> :issue "score"] ?score]})

    (jdbc/execute! ds (sql/format query ["10"]))

Expected Behavior:

    The query should execute successfully, returning rows where the score field equals "10".

Actual Behavior:

    The following error is thrown:

    graphql

    ERROR: could not determine polymorphic type because input has type unknown

Analysis:

    The error suggests that PostgreSQL cannot infer the type of the parameter ?score because it is of type unknown.
    This issue seems to be related to how pg2 handles parameter placeholders and type inference with JSONB functions and operators.
    When using next.jdbc and honeysql, the same query executes without errors.

Workaround Attempts:

    Explicit Casting: Adding explicit type casts to the parameter does not resolve the issue.

    clojure

;; Attempt to cast the parameter to text
:where [:= [:->> :issue "score"] [:cast ?score :text]]

    This results in the same error.

Using Inline Values: Replacing the parameter with an inline value works, but this is not ideal for queries that require parameterization.

clojure

    :where [:= [:->> :issue "score"] "10"]

Additional Information:

    Environment:
        pg2 version: `0.1.17`
        PostgreSQL version: `16.3`
        Clojure version: `1.11`

Request:

    Is there a way to correctly handle parameter types with JSONB functions and operators in pg2?
    If this is a bug, could it be addressed in a future update?
    Any guidance or suggestions would be greatly appreciated.

Thank you for your assistance!

**Comment by igrishaev** [comment]
Hm, interesting. Let me reproduce it locally...

**Comment by igrishaev** [comment]
Just wondering if this text was generated with ChatGPT? Because it looks a bit strange. First, the query you posted above is incorrect. If you try to run it, you'll get an error. 

This version looks closer to what you want:

```clojure
(def query
  {:select [[:->> :issue "score"] :score]
   :from   [[[:jsonb_array_elements :data] :issue]]
   :where  [:= [:->> :issue "score"] ?score]})
```

I wrote a couple of new tests trying to reproduce it but I couldn't as they work fine. Here are two examples:

```clojure
(deftest test-client-json-function-params
  (pg/with-connection [conn *CONFIG-TXT*]

    (pg/execute conn "create temp table foo123 (val jsonb)")
    (pg/execute conn "insert into foo123 values ($1)" {:params [{:foo {:bar {:kek 123}}}]})

    (let [res (pg/execute conn "select val #>> array['foo', 'bar', 'kek'] as val from foo123")]
      (is (= [{:val "123"}] res)))

    (let [res (pg/execute conn
                          "select val #>> array[$1, $2, $3] as val from foo123"
                          {:params ["foo" "bar" "kek"]})]
      (is (= [{:val "123"}] res)))

    (let [res (pg/execute conn
                          "select val #>> $1 as val from foo123"
                          {:params [["foo" "bar" "kek"]]})]
      (is (= [{:val "123"}] res)))))


;;
;; https://github.com/igrishaev/pg2/issues/17
;;
(deftest test-client-json-function-params-case-2

  (pg/with-connection [conn *CONFIG-TXT*]

    (pg/execute conn "create temp table test (data jsonb)")
    (pg/execute conn "insert into test values ($1)"
                {:params [[{:score "10" :quality "high"}
                           {:score "8" :quality "medium"}]]})

    (let [sql-map
          '{:select [[[:->> :issue "score"] :score]]
            :from   [[[:jsonb_array_elements ?data] :issue]]
            :where  [:= [:->> :issue "score"] ?score]}

          sql-vec
          (sql/format sql-map
                      {:params {:data [{:score "10" :quality "high"}
                                       {:score "8" :quality "medium"}]
                                :score "10"}})

          res
          (jdbc/execute! conn sql-vec)]

      (is (= [{:score "10"}] res)))))
```

**Comment by igrishaev** [comment]
Could you please provide a real, working query that causes the error you mentioned?

**Comment by igrishaev** [comment]
Another working case:


```clojure
    (let [sql-map
          '{:select [:issue]
            :from   [[{:select [[[:jsonb_array_elements :data] :issue]]
                       :from [:test]}
                      :sub]]
            :where  [:= [:->> :issue "score"] "10"]}

          sql-vec
          (sql/format sql-map
                      {:params {:data [{:score "10" :quality "high"}
                                       {:score "8" :quality "medium"}]
                                :score "10"}})

          res
          (jdbc/execute! conn sql-vec)]

      (is (= [{:issue {:score "10", :quality "high"}}] res)))
```
