### ISSUE TITLE
Implement SASL SCRAM SHA 256 PLUS

### ISSUE THREAD

**Issue by thenonameguy** [igrishaev/pg2#21]
It's currently not possible to connect to neon.tech Postgres databases, for the lack of this support.

I'll have a stab at implementing it, will open a PR.

**Comment by igrishaev** [comment]
Implementing the PLUS version of SASL SCRAM would be amazing! I tried it once but didn't manage to make it work. Could you please take this file as a reference? https://github.com/igrishaev/pg2/blob/master/pg-core/src/java/org/pg/auth/ScramSha256.java

Ideally, your implementation should follow it's structure. It's a static file with methods called step1, step2, etc. Then you reuse that class in the auth pipeline:

https://github.com/igrishaev/pg2/blob/master/pg-core/src/java/org/pg/Connection.java#L766

In the "handleAuthenticationSASL" method of the Connection class, you extend the "isScramSha256Plus" branch.

**Comment by thenonameguy** [comment]
https://github.com/ongres/scram would you be willing to accept a PR that uses this dependency, instead of hand-rolling this auth method? PGJdbc uses the same library.

**Comment by igrishaev** [comment]
I'd like to clarify: do you really get an error when connecting a neon.tech-hosted database? I've checked the docs and they say, they use SCRAM 256. They don't mention the PLUS version of the algorithm:

https://neon.tech/blog/serverless-driver-for-postgres

Could please share an error that appears when connecting the database?

**Comment by thenonameguy** [comment]
Sure, here you go:
```
SASL SCRAM SHA 256 PLUS method is not implemented yet
 :via
 [{:type org.pg.error.PGError
   :message SASL SCRAM SHA 256 PLUS method is not implemented yet
   :at [org.pg.Connection handleAuthenticationSASL Connection.java 772]}]
 :trace
 [[org.pg.Connection handleAuthenticationSASL Connection.java 772]
  [org.pg.Connection handleMessage Connection.java 699]
  [org.pg.Connection interact Connection.java 671]
  [org.pg.Connection interact Connection.java 681]
  [org.pg.Connection authenticate Connection.java 227]
  [org.pg.Connection <init> Connection.java 80]
  [org.pg.Connection <init> Connection.java 85]
  [pg.core$connect invokeStatic core.clj 393]
  [pg.core$connect invoke core.clj 383]
```

Using these connect params:
```
{:host ep-round-pond-a2yzni81.eu-central-1.aws.neon.tech, :port 5432, :database schemamap-demo, :user schemamap-demo_owner, :so-timeout 3000, :use-ssl? true}
```

When connecting with psql, this is the SSL connection that's built up:
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, compression: off)

**Comment by igrishaev** [comment]
Grief, they don't allow the standard "SCRAM-SHA-256" algorithm. 

I spent some time on looking at the library you shared above. In general, implementing our own version of -PLUS algorithm won't be difficult because I already have non-PLUS code working.

The real problem is, the -PLUS method accepts something which is called `bindingData`. This is a byte array fetched from a socket. The library doesn't care about how this data was fetched. It's done on JDBC side by this method:

https://github.com/jorsol/pgjdbc/blob/2f7511504c8eff34e55ed4b72df369687a09e3a8/pgjdbc/src/main/java/org/postgresql/core/v3/ScramAuthenticator.java#L95

**Comment by igrishaev** [comment]
The most critical part of the code is the following:

```java
      SSLSession session = ((SSLSocket) socket).getSession();
      try {
        Certificate[] certificates = session.getPeerCertificates();
        if (certificates != null && certificates.length > 0) {
          Certificate peerCert = certificates[0]; // First certificate is the peer's certificate
          if (peerCert instanceof X509Certificate) {
            X509Certificate cert = (X509Certificate) peerCert;
            return TlsServerEndpoint.getChannelBindingData(cert);
          }
        }
```

and here is an excerpt from the library:

```java
  public static byte @NotNull [] getChannelBindingData(final @NotNull X509Certificate serverCert)
      throws CertificateEncodingException {
    MessageDigest digestAlgorithm = getDigestAlgorithm(serverCert.getSigAlgName());
    if (digestAlgorithm == null) {
      return new byte[0];
    }
    return digestAlgorithm.digest(serverCert.getEncoded());
  }
```

If I have this working in PG2, than I'll be able to implement the -PLUS version of SCRUM

**Comment by igrishaev** [comment]
@thenonameguy Once you confirm it works, I'll close that issue and will create another one to implement -PLUS version scram.

**Comment by thenonameguy** [comment]
![Screenshot 2024-11-05 at 09 45 05](https://github.com/user-attachments/assets/14cfa6b8-06ba-4017-8695-09315af0d420)

Works, thanks so much!

**Comment by igrishaev** [comment]
Cool, closing in favor of #22

**Comment by Neustradamus** [comment]
@igrishaev: Good job for your commits!

Merged commits:
- https://github.com/igrishaev/pg2/commit/2bd89708355511b1584ba11e7bddb114ef51189f
- https://github.com/igrishaev/pg2/commit/8e2c6e8662b12a782701b787b1745d28a94603a4
- https://github.com/igrishaev/pg2/commit/ce4c38ce60fb5af5b78ca9f9b947914e48c9ac65

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/igrishaev/pg2/issues/21
- https://github.com/igrishaev/pg2/issues/22
