### ISSUE TITLE
org.pg.error.PGErrorResponse extends Error

### ISSUE THREAD

**Issue by kolstae** [igrishaev/pg2#6]
This is just hard to use. Errors are reserved for OOMs and stuff that's not to be handled. 

Perhaps this could inherit Exception?

**Comment by igrishaev** [comment]
Yes I'll fix it soon.

**Comment by igrishaev** [comment]
I think it should extend RuntimeException. I don't want it to be checked

**Comment by igrishaev** [comment]
It has been solved in 1.6.0.
