### ISSUE TITLE
Readme mentions two different migration formats?

### ISSUE THREAD

**Issue by teodorlu** [igrishaev/pg2#7]
Hi! While reading about migrations in the README, I noticed a thing that may not have been intentional.

As of 2b2ed2d96de64fbb1b72efa2d32fdc1422d446f9, I see two different migration SQL file formats metioned:

- with dots: https://github.com/igrishaev/pg2/blob/2b2ed2d96de64fbb1b72efa2d32fdc1422d446f9/README.md#L1963
- with dashes: https://github.com/igrishaev/pg2/blob/2b2ed2d96de64fbb1b72efa2d32fdc1422d446f9/README.md#L1981-L1983

Was this intentional?

**Comment by igrishaev** [comment]
Good catch: the `001-create-users.next.sql` name is a mistake. The pattern `<id>.<slug>.<direction>.sql` is correct. Let me fix that in readme.

**Comment by igrishaev** [comment]
It has been fixed in 1.7.0 (naming and file parsing). Again, thank you for spotting it!
